spring:
  cloud:
    openfeign:
      client:
        config:
          poupa-compra-api:
            url: ${URL_POUPA_COMPRA_API}
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full