server:
  port: 8181
spring:
  address: 0.0.0.0
  cloud:
    openfeign:
      client:
        config:
          poupa-compra-api:
            url: http://poupacompra-integracao:8182
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full